[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26" # Recommended for v4
evm_version = "cancun"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }