[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
broadcast = "broadcast"

remappings = [
  "forge-std/=lib/forge-std/src/",
  "v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/src/",
]